### ISSUE TITLE
Running deepgo stand-alone vs. webserver

### ISSUE THREAD

**Issue by WardDeb** [bio-ontology-research-group/deepgo#10]
Hi,

I've managed to get all correct versions of libraries to run deepgo standalone on our cluster. At first glance it seems to be working ok. Regarding the output generated after calling predict_all, the TSV does not seem to have scores embedded like the web based output does. Is it safe to assume a certain cut-off is already called in the stand-alone version, and that I can take the GO terms called as true hits? 

Kind regards,

Ward

**Comment by coolmaksat** [comment]
Hi,
predict_all uses threshold of 0.3 (it is set on line 100). This threshold resulted in highest Fmax measure. 
You can lower the threshold to get more predictions, but it might result in more false positives.

**Comment by WardDeb** [comment]
Great, Thanks for the quick response!
