### ISSUE TITLE
How to map ngrams back animo acids. 

### ISSUE THREAD

**Issue by datduong** [bio-ontology-research-group/deepgo#14]
In ngrams.py, there is a pickle file that contains the mapping of 3-kmer into amino acids 

The file `df.to_pickle('data/cafa3/ngrams.pkl')` at line `https://github.com/bio-ontology-research-group/deepgo/blob/master/ngrams.py#L24`. 

Is this file available for download? I extracted the data tar, but did not see this file. 

Thanks.

**Comment by coolmaksat** [comment]
Hi, you can find it here http://deepgo.bio2vec.net/data/models/

**Comment by datduong** [comment]
Thanks.
