### ISSUE TITLE
Are you keeping the vectors in Protein-protein network fixed throughout the experiment? 

### ISSUE THREAD

**Issue by datduong** [bio-ontology-research-group/deepgo#18]
I work in Pytorch and so I am not 100% familiar with Keras. I see that you merge the sequence embedding and the protein embedding in [your code here](https://github.com/bio-ontology-research-group/deepgo/blob/master/nn_hierarchical_network.py#L288). 

Here, `Input1` which is amino sequence embedding will get updated (as we expect). However, will the vectors of the protein-protein network (the `Input2`) also get updated during training? Thanks.

**Comment by coolmaksat** [comment]
Hi, network embeddings are fixed

**Comment by datduong** [comment]
Thanks.
