### ISSUE TITLE
BLAST alternatives

### ISSUE THREAD

**Issue by xibalbanus** [bio-ontology-research-group/deepgo#4]
Good day,

I was wondering if it would be possible to tweak the software to use other programs as an alternative to BLAST (e.g. diamond, GPUblast, etc.).

I attempted to do a simple modification of the following code in preditct_all.py to do so with diamond, but I ran into some other issues downstream (I think it has to do with diamond not piping stdin/stdout properly). Any suggestions?

    p = Popen(['blastp', '-db', 'data/embeddings.fa',
               '-max_target_seqs', '1', '-num_threads', '4',
               '-outfmt', '6 qseqid sseqid'], stdin=PIPE, stdout=PIPE)

Best,
J.

**Comment by coolmaksat** [comment]
Hi,
Could you please elaborate more specific on the issues. In general, any blast similar program should work. If it doesn't read/write to stdin/stdout then files can also be used.

**Comment by coolmaksat** [comment]
The latest version uses diamond.
