### ISSUE TITLE
Requirements.txt containing wrong versions of modules?

### ISSUE THREAD

**Issue by WardDeb** [bio-ontology-research-group/deepgo#5]
Hi,

I'm trying to run deepgo standalone, however I noticed that Keras 1.2.2 rather than 2.1.3 is required (ran into some compatibility issues), at the moment I'm also running with tensorflow 1.1.0 instead of 1.2.0, but I'm not sure if this is required or not. Maybe the data available at http://deepgo.bio2vec.net/data/ is not yet up to date with the github?

Kind regards

**Comment by coolmaksat** [comment]
Hi, we are currently updating the model together with libraries. I reset the master branch to the latest stable version. You need to install tensorflow 0.12.0rc0 and keras 1.1.2 and use predict_all.py script to run the application. Let me know if you have any problems.

**Comment by WardDeb** [comment]
Hi, thanks for the quick response. I'll try running with the specific versions and report back. Cheers!
