### ISSUE TITLE
Something about training the model

### ISSUE THREAD

**Issue by wocnb** [bio-ontology-research-group/deepgo#6]
Good day,
I was trying to training deepgo by myself, but there are some files that's can't download in http://deepgo.bio2vec.net/data/ , like mouse-sequence.pkl and some others. I wondered where should I find these files.
Thank you.

**Comment by coolmaksat** [comment]
Hi,
We only published trained models and data required to run them. Most of the .pkl files were generated during training from swissprot sequences and annotations downloaded from uniprot.org. Have a look at get_data.py get_functions.py and cafa.py

**Comment by wocnb** [comment]
That's helps a lot, thank you very much

**Comment by lucamasera** [comment]
Could you maybe share an example folder and a script for retraining your model? It would be extremely useful.
Thank you

**Comment by coolmaksat** [comment]
The script for retraining the model is nn_hierarchical_network.py. The training/testing data can be found in data file (see README)
