### ISSUE TITLE
AttributeError: 'module' object has no attribute 'select'

### ISSUE THREAD

**Issue by cartal** [bio-ontology-research-group/deepgo#7]
Hi, 

I can't get around this error. I have tried to solve it by upgrading tf version but it is not working with the newest versions of tf. 

Any idea of a workaround? 

Regards

**Comment by coolmaksat** [comment]
Hi,
You should probably downgrade tf version, look at requirements.txt

**Comment by cartal** [comment]
Hi again, 

I have spend this time trying to solve the installation problem. And I thought I did, but I get this error (See attachment). 

Also, I must be missing something, but I don't find a sequential set of steps to perform the analysis. Which script do I have to use to train the model and how. Is this somewhere?



![screen shot 2018-05-22 at 13 30 30](https://user-images.githubusercontent.com/3297906/40362433-73d3078c-5dc4-11e8-8363-d2dbd10cf210.png)

**Comment by coolmaksat** [comment]
Hi, the script you are using is the one which is used for training and testing the model (which use only protein sequence). This file has training data http://deepgo.bio2vec.net/data/train.tar.gz
