### ISSUE TITLE
data.tar.gz not containing FFPred3 

### ISSUE THREAD

**Issue by amityaffliction** [bio-ontology-research-group/deepgo#9]
Hi I was looking for way to compare performance of FFPred3. There is GOFDR folder in data.tar.gz but no FFPred3. Can you tell me way to evaluate as README suggests?

and there are some confusions. code suggests DATA_ROOT is 'data/swiss/' so data.tar.gz file's contents must be in data/swiss/ ? 

and do we have to manually change code of evaluate.py to compare with other methods?

Thank you.

by the way great work!

**Comment by coolmaksat** [comment]
Hi, you can donwload FFPred predictions for CAFA3 from here http://bioinfadmin.cs.ucl.ac.uk/downloads/ffpred/cafa3/

**Comment by coolmaksat** [comment]
data.tar.gz contains our evaluation data, the contents of DATA_ROOT you can find here http://deepgo.bio2vec.net/data/
